# This the the property graph format script for PandaDB-v0.3 test
# source node format: id(long)
# target neo4j node format: id_s(long),id_p(long),str(string),flag(bool)
# note: id_p means a property, whose name is id.
# note: str is generated by id, with the map(0>a, 1->b, ...... 9->j)
# note: flag = id%2, 0 for false, 1 for true;
