import time
# This the the property graph format script for PandaDB-v0.3 test
# source node format: id(long)
# target neo4j node format: id_s(long), label(str), id_p(long),idStr(string),flag(bool)
# target neo4j edge format: fromId(long), type(str), toId(long), fromIn_p(long), toId_p(str), category(int)
# note: id_p means a property, whose name is id.
# note: str is generated by id, with the map(0>a, 1->b, ...... 9->j)
# note: flag = id%2, 0 for false, 1 for true;
# WARNING: the comma(,) is preserved split symbol!!! Don't use it in prop!!!

def id2str(id) -> str:
    idStr = ""
    while (id > 0):
        bit = id % 10
        idStr += chr(int(bit + 97))
        id = int(id / 10)
    return "".join(reversed(idStr))

def wrapPandaNode(nodePath:str):
    with open(nodeHeadPath, mode="w+", encoding='utf-8') as target:
        head = "id_s:ID,label:LABEL,id_p:long,idStr:string,flag:boolean\n"
        target.write(head)
    with open(nodePath, mode="r", encoding='utf-8') as source:
        with open(targetNodePath, mode="w+", encoding='utf-8') as target:
            i = 0
            for item in source:
                if (i % pow(10, 7) == 0): print("{}% nodes generated.".format(i / pow(10, 7))); i += 1
                id = int(item)
                id_s = id
                node_label = "label"+str(id%10)
                id_p = id
                idStr = id2str(int(id))
                flag = bool(id % 2)
                line = "{},{},{},\"{}\",{}\n".format(id_s, node_label, id_p, idStr, flag)
                target.write(line)

# def wrapPandaEdge(edgePath:str):
#     with open(edgePath, mode='r', encoding='utf-8') as source:
#         with open(edgePath+"-wrapped.csv", mode="w+", encoding='utf-8') as target:
#             head = "fromId:START_ID,type:TYPE,toId:END_ID,fromId_num:long,toId_str,weight:int\n"
#             target.write(head)
#             # for i in range(100):
#             i = 0
#             for item in source:
#                 if (i % pow(10, 7) == 0): print("{}% nodes generated.".format(i / pow(10, 7)))
#                 s_line = item.replace("\n", "").split("\t")
#                 # s_line = source.readline().replace("\n", "").split("\t")
#                 fromId = int(s_line[0])
#                 edgeType = "type" + str(fromId % 10)
#                 toId = int(s_line[1])
#                 fromId_p = fromId
#                 toId_p = str(toId)
#                 category = fromId%10
#                 line = "{},\"{}\",{},{},\"{}\",{}\n".format(fromId, edgeType, toId, fromId_p, toId_p, category)
#                 target.write(line)

def wrapPandaEdge(edgePath:str):
    with open(edgeHeadPath, mode="w+", encoding='utf-8') as target:
        head = "relId,fromId:START_ID,toId:END_ID,type:TYPE,fromId_num:long,toId_str,weight:int\n"
        target.write(head)
    with open(edgePath, mode='r', encoding='utf-8') as source:
        with open(targetEdgePath, mode="w+", encoding='utf-8') as target:
            relId = 0
            i = 0
            for item in source:
                if (i % pow(10, 7) == 0): print("{}% edges generated.".format(i * 0.5 / pow(10, 7))); i += 1
                s_line = item.replace("\n", "").split(",")
                fromId = int(s_line[0])
                edgeType = "type" + str(fromId % 10)
                toId = int(s_line[1])
                fromId_p = fromId
                toId_p = str(toId)
                category = fromId%10
                line = "{},{},{},{},{},{},{}\n".format(relId, fromId, toId, edgeType, fromId_p, toId_p, category)
                target.write(line)
                relId += 1


srcNodePath = "./nodes-1B.csv"
srcEdgePath = "./edges-1B.csv"
targetNodePath = "G://dataset//nodes-1B-wrapped.csv"
nodeHeadPath = "G://dataset//nodes-1B-wrapped-head.csv"
targetEdgePath = "G://dataset//edges-1B-wrapped.csv"
edgeHeadPath = "G://dataset//edges-1B-wrapped-head.csv"

def main():
    print("-------start to wrap nodes----------")
    localtime1 = time.asctime(time.localtime(time.time()))
    wrapPandaNode(srcNodePath)
    with open(targetNodePath) as nodeFile:
        print("wrapped node file:\n")
        for i in range(10):
            print(nodeFile.readline())

    print("-------start to wrap edges----------")
    localtime2 = time.asctime(time.localtime(time.time()))
    wrapPandaEdge(srcEdgePath)
    with open(targetEdgePath) as edgeFile:
        print("wrapped edge file:\n")
        for i in range(10):
            print(edgeFile.readline())
    localtime3 = time.asctime(time.localtime(time.time()))
    print("-------end----------")
    print(localtime1)
    print(localtime2)
    print(localtime3)

if __name__ == '__main__':
    main()